appIMDb/urls.py
"""Define los patrones URL para la app, appIMDb."""

from django.urls import path

from . import views

app_name = 'appIMDb'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Pagina que muestra todas las peliculas.
    path('peliculas/', views.peliculas, name='peliculas'),
    # Pagina detallada para una pelicula individual.
    path('peliculas/<int:pelicula_id>/', views.pelicula, name='pelicula'),
    # Pagina que muestra todas las peliculas ordenadas por calificacion, de mayor
    # a menor.
    path('peliculas/rating', views.peliculasRating, name='peliculasRating'),
    # Pagina que muestra todas las peliculas ordenadas por el numero de usuarios
    # que las ha marcado como favoritas, de mayor a menor.
    path('peliculas/favoritos', views.peliculasFavorito, name='peliculasFavorito'),
    # Pagina que muestra todos los generos.
    path('generos/', views.generos, name='generos'),
    # Pagina que muestra todas las peliculas de un genero.
    path('generos/<int:genero_id>/', views.genero, name='genero'),
    # Pagina para escribir una review.
    path('review/<int:pelicula_id>/', views.nuevaReview, name='nuevaReview'),
    # Pagina para editar una review.
    path('review/editar/<int:review_id>/', views.editarReview, name='editarReview'),
    # Pagina para borrar una review.
    path('review/borrar/<int:review_id>/', views.borrarReview, name='borrarReview'),
]

clon_imdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('appIMDb.urls')),
]

users/urls.py
""" Define los patrones URL para users. """

from django.urls import path, include

from . import views

app_name = "urls"
urlpatterns = [
    # Incluye las urls de auth default.
    path('', include('django.contrib.auth.urls')),
    # Pagina para crear una cuenta.
    path('registro/', views.registro, name='registro'),
    # Pagina para visualizar las peliculas favoritas.
    path('perfil/favoritas', views.listaFav, name='listaFav'),
    # Pagina para agregar a favoritos.
    path('fav/<int:pelicula_id>/', views.marcarFav, name='marcarFav', ),
]

appIMDb/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Genero(models.Model):
    """Un genero de pelicula."""

    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'generos'

    def __str__(self):
        """Devuelve una representacion en cadena del genero."""

        return f"{self.nombre}"

class Pelicula(models.Model):
    """Una pelicula con sus caracteristicas y portada."""

    titulo = models.CharField(max_length=100, unique=True)
    # Considere un limite de 50 caracteres por que los titulos suelen ser cortos, 
    # pero opte por 100 para mantener el nombre original de las peliculas que
    # excedan este numero sin modificar el nombre, como por ej.:
    #   Indiana Jones and the Kingdom of the Crystal Skull (50 caracteres)
    #   Borat: Cultural Learnings of America for Make 
    #       Benefit Glorious Nation of Kazakhstan (83 caracteres)

    codigo = models.CharField(max_length=10, unique=True)
    # IMDb le otorga un codigo de 9 caracteres a todas las peliculas en su base de datos.
    # Este codigo funciona para encontrar mas informacion sobre una pelicula,
    # ignorando el lenguaje del idioma y eliminando la necesidad de 'adivinar'
    # el nombre de la pelicula en otro idioma.
    # Ejemplos de diferentes casos:
    #   - El mejor de los casos:
    #       Nombre original: "Iron Man"
    #       Nombre espaniol: "Iron Man"
    #       
    #       En este caso, el titulo original de la pelicula es el mismo en todo el 
    #       mundo.
    #
    #   - El titulo es traducido literalmente:
    #       Nombre original: "Legally Blonde"
    #       Nombre espaniol: "Legalmente Rubia"
    #
    #       En estos casos, el titulo original es traducido y podemos encontrar mas
    #       informacion de la pelicula solo asumiendo que se traduce el nombre.
    #
    #   - El titulo es completamente diferente:
    #       Nombre original: "John Wick"
    #       Nombre espaniol: "Otro dia para matar"
    #       
    #       En estos casos, el titulo es completamente diferente, ya sea por razones
    #       de marketing o por que el nombre viene de una lengua con un alfabeto
    #       diferente.

    genero = models.ForeignKey(Genero, on_delete=models.CASCADE)
    # Cada pelicula solo puede tener un genero.

    anio = models.PositiveSmallIntegerField()
    # El rango de este campo es de 0 a 32767.
    # Adecuado al rango con el que estaremos trabajando (0 a 2XXX)

    sinopsis = models.TextField(max_length=500) # Limite de 500 caracteres.

    portada = models.URLField(max_length=200) # Limite por default de Django
    # Uso URLField por que las portadas estaran almacenadas en un servidor externo.

    favoritos = models.ManyToManyField(
        User, related_name='favorito', default=None, blank=True
    ) # Almacena los id's de los usuarios que la han marcado como favorita.

    class Meta:
        verbose_name_plural = 'peliculas'

    def __str__(self):
        """Regresa una representacion en cadena del 'titulo' del modelo."""

        if len(self.titulo) > 50:
            return f"{self.titulo[:50]}..."
        else:
            return f"{self.titulo}"


class Review(models.Model):
    """Una review de un usuario para una pelicula."""

    usuario =  models.ForeignKey(User, on_delete=models.CASCADE)

    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE)

    texto = models.TextField(null=True, blank=True)
    # No tiene un limite actual, pero considerare un limite.

    calificacion = models.PositiveSmallIntegerField(validators=[MinValueValidator(0),
                                                                MaxValueValidator(10)])
    # Votos del 1 al 10
    # Se elige este rango por que funciona para dos tipos de visualizacion:
    #       - Una calificacion del 1 al 10
    #       - Una representacion en 'estrellas', de 1 a 5.
    #       Ejemplo:
    #           Calificacion: 8
    #               Representacion 1 a 10: 8
    #               Representacion estrellas: 4
    #                   - Se divide la calificacion en 2, 
    #       Tambien, permite la representacion de medias estrellas:
    #               Representacion 1 a 10: 9
    #               Representacion estrellas: 4.5 ( 9 / 2 = 4.5 )
    #
    # Asimismo, si redondeamos el resultado de dividir la calificacion base10,
    # se podria redondear a las representaciones adecuadas en estrellas.
    # Ejemplo:
    #       Repr. 1 a 10: 6.8
    #           (6.8 / 2 = 3.4)
    #       Repr. estrellas: 3.5 o 3

    fecha = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'reviews'

    def __str__(self):
        """Regresa una representacion en cadena de la review."""

        # En caso de que la review supere los 50 caracteres, aniade 
        # puntos suspensivos.
        if len(self.texto) > 50:
            return f"{self.usuario}: {self.texto[:50]}..."
        else:
            return f"{self.usuario}: {self.texto}"

appIMDb/forms.py
from django import forms

from .models import Review

class ReviewForm(forms.ModelForm):
    """ El formulario para crear una resenia. """

    class Meta:
        model = Review
        fields = ['pelicula', 'texto', 'calificacion']
        labels = {'pelicula': '', 'texto': 'Review', 'calificacion': 'calificacion'}
        widgets = {'texto': forms.Textarea(attrs={'cols': 80})}
        # Sobrescribe el widget default de Django.
        # El widget de texto tiene por default un area de texto de 40 columnas,
        # lo cambio a 80 para que el usuario tenga mas espacio.

appIMDb/views.py
from django.shortcuts import render,  redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404

from .models import Pelicula, Review, Genero
from .forms import ReviewForm

def index(request):
    """ La home page para la app. """
    return render(request, 'appIMDb/index.html')

def peliculas(request):
    """ Muestra todas las peliculas. """
    peliculas = Pelicula.objects.order_by('-anio')

    context = {'peliculas': peliculas}
    return render(request, 'appIMDb/peliculas.html', context)

def pelicula(request, pelicula_id):
    """ Muestra los detalles de una pelicula. """
    pelicula = get_object_or_404(Pelicula, id=pelicula_id)

    # Todas las reviews de la pelicula presentadas por fecha
    # en orden reverso.
    reviews = pelicula.review_set.order_by('-fecha')

    # Este bloque calcula la calificacion otorgada por
    # todas las reviews.
    calificacion = None
    for review in reviews:
        # Si no hay reviews, calificacion se mantiene como None.
        if calificacion == None:
            calificacion = 0
        calificacion += review.calificacion

    # Redondear el numero a 2 decimales
    if calificacion != None:
        # Calcula la calificacion promedio, evita la division de 0 si es el resultado
        # de las sumas. 
        # Si la suma total de calificacion es 0, no hay necesidad de obtener el
        # promedio; todos habrian votado 0.
        if calificacion > 0:
            calificacion = calificacion / len(reviews)
            calificacion = round(calificacion, 2) 

    # Verifica si el usuario la ha marcado como favorita o no
    if pelicula.favoritos.filter(id=request.user.id).exists():
        # Esta flag dira si el usuario la ha marcado como favorita antes.
        favFlag = True
    else:
        favFlag = False

    context = {'pelicula': pelicula, 'reviews': reviews, 'calificacion': calificacion,
                'favFlag': favFlag}
    return render(request, 'appIMDb/pelicula.html', context)

def peliculasRating(request):
    """Muestra todas las peliculas ordenadas por su Rating, 
        en orden de mayor a menor."""

    peliculas = Pelicula.objects.order_by('titulo')

    # Dict para almacenar las peliculas junto a sus calificaciones.
    calificaciones = {}

    for pelicula in peliculas:
        calificaciones[pelicula] = 0
        calificacion = 0
        reviews = pelicula.review_set.order_by('-fecha')
        for review in reviews:
            calificacion += review.calificacion
        if len(reviews) > 0:
            calificaciones[pelicula] = calificacion / len(reviews)
        else:
            calificaciones[pelicula] = 0

    # Organiza el dict de mayor a menor calificacion.
    sortedCalificaciones = dict(sorted(calificaciones.items(),
                                        key=lambda item: item[1],
                                        reverse=True))

    peliculasCalificaciones = sortedCalificaciones.keys()

    context = {'peliculas': peliculasCalificaciones}
    return render(request, 'appIMDb/peliculasRating.html', context)

def peliculasFavorito(request):
    """Muestra todas las peliculas, ordenadas por el numero de usuarios que las
        ha marcado como favoritos, de mayor a menor."""

    peliculas = Pelicula.objects.order_by('titulo')

    # Dict para almacenar las peliculas y su numero de favoritos.
    favoritosDict = {}

    # Calcula el numero de favoritos por pelicula.
    for pelicula in peliculas:
        favoritosDict[pelicula] = 0
        favoritos = pelicula.favoritos.all()
        for favorito in favoritos:
            favoritosDict[pelicula] += 1

    # Organiza el dict de mayor a menor.
    sortedFavoritos = dict(sorted(favoritosDict.items(),
                                    key=lambda item: item[1],
                                    reverse=True))

    context = {'peliculas': sortedFavoritos.keys()}
    return render(request, 'appIMDb/peliculasFavoritos.html', context)
        


def generos(request):
    """Muestra todos los generos de peliculas disponibles."""

    generos = Genero.objects.order_by('nombre')

    context = {'generos': generos}
    return render(request, 'appIMDb/generos.html', context)

def genero(request, genero_id):
    """Muestra todas las peliculas de un genero elegido."""

    genero = get_object_or_404(Genero, id=genero_id)

    peliculas = genero.pelicula_set.order_by('titulo')

    context = {'genero': genero, 'peliculas': peliculas}
    return render(request, 'appIMDb/genero.html', context)

@login_required
def nuevaReview(request, pelicula_id):
    """ Aniade una nueva review a una pelicula. """

    pelicula = get_object_or_404(Pelicula, id=pelicula_id)

    # Este bloque verificara si el usuario ha subido una review para esta pelicula
    # antes y en lugar de permitirle subir una nueva, lo redireccionara para
    # que edite esa review.
    # Esto se hace para que los usuarios solo puedan dejar un review por pelicula,
    # y asi, no manipular la calificacion de la pelicula.
    # Por muy buena que este Morbius, vivimos en una democracia.

    # Filtra las reviews de la pelicula, para checar si el usuario ha hecho una
    # review antes para esta pelicula.
    review = pelicula.review_set.filter(usuario=request.user)

    # Un queryset vacio es falsy, por lo que solo se ejecutaria si existe una
    # review previa. Se toma el id de esta y se redirecciona a editarla.
    if review:
        return redirect('appIMDb:editarReview', review_id=review[0].id)


    if request.method != 'POST':
        # No se ha subido la informacion; crea un formulario en blanco.
        form = ReviewForm(initial={'pelicula': pelicula})
    else:
        # Datos POST subidos; procesar informacion.
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            nuevaReview = form.save(commit=False)
            nuevaReview.pelicula = pelicula
            nuevaReview.usuario = request.user
            nuevaReview.save()
            return redirect('appIMDb:pelicula', pelicula_id=pelicula_id)

    # Muestra un formulario en blanco o invalido.
    context = {'pelicula': pelicula, 'form': form}
    return render(request, 'appIMDb/nuevaReview.html', context)

@login_required
def editarReview(request, review_id):
    """Edita una review existente"""

    review = get_object_or_404(Review, id=review_id)

    # Verifica que la review por editar sea del usuario.
    if review.usuario != request.user:
        raise Http404

    pelicula = review.pelicula

    if request.method != 'POST':
        # Request inicial, pre-llena el formulario con la review actual.
        form = ReviewForm(instance=review)
    else:
        # Datos POST subidos; procesa los datos.
        form = ReviewForm(instance=review, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('appIMDb:pelicula', pelicula_id=pelicula.id)

    context = {'review': review, 'pelicula': pelicula, 'form': form}
    return render(request, 'appIMDb/editarReview.html', context)

@login_required
def borrarReview(request, review_id):
    """Elimina una review existente."""
    review = get_object_or_404(Review, id=review_id)

    pelicula = get_object_or_404(Pelicula, id=review.pelicula.id)
    # Verifica que la review por borrar sea del usuario.
    if review.usuario.username == request.user.username:
        review.delete()
        return redirect('appIMDb:pelicula', pelicula_id=pelicula.id)
    else:
        raise PermissionDenied

appIMDb/templates/appIMDb/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <title>Clon IMDb</title>
    <link rel="stylesheet" href="{% static 'appIMDb/styles.css' %}">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}

  
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous">
    </script>

  </head>

  <body style="background-color: #1C1C1C; color: white;">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top"
    style="background-color: #1F2937;">
      <a class="navbar-brand" href="{% url 'appIMDb:index' %}" 
        style="padding-left: 1vh;">
        Clon IMDb
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" 
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
              style="margin-right: 1vh;">
        <span class="navbar-toggler-icon">
        </span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Acceso a las peliculas -->
        <ul class="navbar-nav mr-auto me-auto mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'appIMDb:peliculas' %}">
                Peliculas
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'appIMDb:generos' %}">
                Generos
              </a>
            </li>
        </ul>
        <!-- Opciones de usuario -->
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <span class="navbar-text">
              Hola, {{ user.username }}.
            </span>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:listaFav' %}">
                Favoritos
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">
                Cerrar sesion
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:registro' %}">
                Registrate
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">
                Accede a tu cuenta
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom" style="padding-top: 60px;">
          {% block page_header %}
          {% endblock page_header %}
      </div>
      <div>
          {% block content %}
          {% endblock content %}
      </div>
  </main>
  </body>
</html>

appIMDb/templates/appIMDb/generos.html
{% extends 'appIMDb/base.html' %}

{% block page_header %}
    <h1 class="display-2">
        <div class="fw-bold" style="text-align: center;">
            Generos
        </div>
    </h1>
{% endblock page_header %}

{% block content %}

    <div class="list-group">
        {% for genero in generos %}
            <a href="{% url 'appIMDb:genero' genero.id %}"
                class="list-group-item list-group-item-action text-center display-6">
                {{ genero }}
            </a>
        {% empty %}
            <p class="list-group-item list-group-item-action text-center display-6">
                Aun no se ha registrado ningun genero.
            </p>
        {% endfor %}
    </div>

{% endblock content %}

appIMDb/templates/appIMDb/index.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Clon IMDb</title>
  </head>

  <body>
    {% extends "appIMDb/base.html" %}

    {% block page_header %}
      <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold text-center">
          Clon IMDb
        </h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">
            Clon de IMDb creado usando Python, Django y Bootstrap.
            <br>
            Esta es una WebApp CRUD, los usuarios pueden dejar reviews y calificar
             las peliculas.
          </p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <a class="btn btn-lg btn-secondary px-4 gap-3" 
                href="{% url 'appIMDb:peliculas' %}"
                role="button">
                Peliculas
              </a>
              <a class="btn btn-lg btn-secondary px-4 gap-3" 
                href="{% url 'appIMDb:generos' %}"
                role="button">
                Generos
              </a>
            </div>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-4">
              {% if user.is_authenticated %}
              {% else %}
                <a href="{% url 'users:login' %}"
                  class="btn btn-lg btn-primary px-4 gap-3"
                  role="button">
                  Inicia sesión
                </a>
                <a href="{% url 'users:registro' %}"
                  class="btn btn-lg btn-primary px-4 gap-3">
                  Registrate
                </a>
              {% endif %}
            </div>
        </div>
      </div>
    {% endblock page_header %}

    {% block content %}
    {% endblock content %}
  </body>
</html>

appIMDb/templates/appIMDb/pelicula.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Pelicula</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .checked {
        color: orange;
      }
    </style>
  </head>


  <body style="background-color: #1C1C1C; color: white;">
    {% extends "appIMDb/base.html" %}

    {% block page_header %}

      <div class="header">
        <div class="content">
          <div class="image">
            <img style="width: 35vh; height: auto;" 
              src="{{ pelicula.portada }}" 
              alt="Portada">
          </div>
          <div class="text">
            <div class="title">
              <div class="main">
                {{ pelicula }}
              </div>
              <div class="subtext">
                {{ pelicula.anio }}
              </div>
            </div>
            <div class="bottom-title">
              <div class="rating">
                {% if calificacion %}
                  <div class="fa fa-star checked">
                    {{ calificacion }} / 10
                  </div>
                {% else %}
                  <a href="{% url 'appIMDb:nuevaReview' pelicula.id %}"
                    class="btn btn-outline-primary btn-sm fa fa-star"
                    role="button">
                    Se el primero en calificarla
                  </a>
                {% endif %}
              </div>
              <div class="favorito">
                {% if user.is_authenticated %}
                  {% if favFlag %}
                    <a href="{% url 'users:marcarFav' pelicula.id %}"
                      class="btn btn-danger btn-sm"
                      role="button">
                      Quitala de tus favoritos
                    </a>
                  {% else %}
                    <a href="{% url 'users:marcarFav' pelicula.id %}"
                      class="btn btn-primary btn-sm"
                      role="button">
                      Agregala a tus favoritos
                    </a>
                  {% endif %}
                {% endif %}
              </div>
              <div class="genero">
                <a href="{% url 'appIMDb:genero' pelicula.genero.id %}"
                  class="btn btn-primary btn-sm"
                  role="button">
                  {{ pelicula.genero }}
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% endblock page_header %}

    {% block content %}

      <div class="information">
        <div class="sinopsis">
          {{ pelicula.sinopsis|linebreaks }}
        </div>
        
        <div class="reviews">
          <div class="hacer-review d-grid">
            <a href="{% url 'appIMDb:nuevaReview' pelicula.id %}"
              class="btn btn-outline-secondary btn-sm"
              role="button">
              Deja una review
            </a>
          </div>
          {% for review in reviews %}
          <div class="review">
            {% if review.texto %}
            <div class="top-review">
              <div class="usuario">
                {{ review.usuario }}:
              </div>
              <div class="review-rating">
                <div class="fa fa-star checked">
                  {{ review.calificacion }} / 10
                </div>
              </div>
            </div>
            <div class="review-texto">
              {{ review.texto}}
            </div>
            {% else %}
              <p>
                Nadie ha escrito una review.
              </p>
            {% endif %}
          </div>
          {% empty %}
            <p>
              Nadie ha dejado una review.
            </p>
          {% endfor %}
        </div>
      </div>

    {% endblock content %}
  </body>
</html>

appIMDb/templates/appIMDb/peliculas.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Peliculas</title>
  </head>

  <body>
    {% extends "appIMDb/base.html" %}

    {% block page_header %}

      <h1 class="display-2">
        <div class="text-center fw-bold">
          Peliculas
        </div>
      </h1>

      <div class="d-grid gap-2 d-md-block text-center btn-group" role="group"
          aria-label="Sorting buttons">
          <a href="{% url 'appIMDb:peliculasRating' %}"
            class="btn btn-outline-primary btn-sm mt-2">
            Por Ratings
          </a>
          <a href="{% url 'appIMDb:peliculasFavorito' %}"
            class="btn btn-outline-primary btn-sm mt-2">
            Por Favoritos
          </a>
      </div>
      
    {% endblock page_header %}

    {% block content %}

    <div class="favoritos">
        {% for pelicula in peliculas %}
            <div class="card" style="width: 18rem;">
                <a href="{% url 'appIMDb:pelicula' pelicula.id %}">
                    <img src="{{ pelicula.portada }}" alt="Portada"
                        class="card-img-top">
                </a>
                <div class="card-body">
                    <p class="card-text titulo">
                        {{ pelicula.titulo }}
                    </p>
                </div>
            </div>
        {% empty %}
            <p>
                Aún no se ha registrado ninguna pelicula.
            </p>
        {% endfor %}
    </div>

    {% endblock content %}
  </body>
</html>

appIMDb/templates/appIMDb/peliculasFavoritos.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Peliculas</title>
  </head>

  <body>
    {% extends "appIMDb/base.html" %}

    {% block page_header %}

    <div class="text-center">
        <h1 class="display-2 fw-bold">
          Peliculas
        </h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead">
            Ordenadas por el numero de usuarios que las ha marcado como favoritas,
             de mayor a menor.
          </p>
        </div>
        <div class="d-grid gap-2 d-md-block text-center btn-group" role="group"
            aria-label="Sorting buttons">
            <a href="{% url 'appIMDb:peliculas' %}"
                class="btn btn-outline-primary btn-sm mt-2">
                Por Año
            </a>
            <a href="{% url 'appIMDb:peliculasRating' %}"
              class="btn btn-outline-primary btn-sm mt-2">
              Por Ratings
            </a>
    </div>
      </div>
      
    {% endblock page_header %}

    {% block content %}

    <div class="favoritos">
        {% for pelicula in peliculas %}
            <div class="card" style="width: 18rem;">
                <a href="{% url 'appIMDb:pelicula' pelicula.id %}">
                    <img src="{{ pelicula.portada }}" alt="Portada"
                        class="card-img-top">
                </a>
                <div class="card-body">
                    <p class="card-text titulo">
                        {{ pelicula.titulo }}
                    </p>
                </div>
            </div>
        {% empty %}
            <p>
                Aún no se ha registrado ninguna pelicula.
            </p>
        {% endfor %}
    </div>

    {% endblock content %}
  </body>
</html>

appIMDb/templates/appIMDb/peliculasRating.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Peliculas</title>
  </head>

  <body>
    {% extends "appIMDb/base.html" %}

    {% block page_header %}

    <div class="text-center">
        <h1 class="display-2 fw-bold">
          Peliculas
        </h1>
        <div class="col-lg-6 mx-auto">
          <p class="display-6 lead">
            Ordenadas por su Rating, <br>de mayor a menor.
          </p>
        </div>
        <div class="d-grid gap-2 d-md-block text-center btn-group" role="group"
            aria-label="Sorting buttons">
            <a href="{% url 'appIMDb:peliculas' %}"
                class="btn btn-outline-primary btn-sm mt-2">
                Por Año
            </a>
            <a href="{% url 'appIMDb:peliculasFavorito' %}"
              class="btn btn-outline-primary btn-sm mt-2">
              Por Favoritos
            </a>
    </div>
      </div>
      
    {% endblock page_header %}

    {% block content %}

    <div class="favoritos">
        {% for pelicula in peliculas %}
            <div class="card" style="width: 18rem;">
                <a href="{% url 'appIMDb:pelicula' pelicula.id %}">
                    <img src="{{ pelicula.portada }}" alt="Portada"
                        class="card-img-top">
                </a>
                <div class="card-body">
                    <p class="card-text titulo">
                        {{ pelicula.titulo }}
                    </p>
                </div>
            </div>
        {% empty %}
            <p>
                Aún no se ha registrado ninguna pelicula.
            </p>
        {% endfor %}
    </div>

    {% endblock content %}
  </body>
</html>