appIMDb/urls.py
"""Define los patrones URL para la app, appIMDb."""

from django.urls import path

from . import views

app_name = 'appIMDb'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Pagina que muestra todas las peliculas.
    path('peliculas/', views.peliculas, name='peliculas'),
    # Pagina detallada para una pelicula individual.
    path('peliculas/<int:pelicula_id>/', views.pelicula, name='pelicula'),
    # Pagina que muestra todas las peliculas ordenadas por calificacion, de mayor
    # a menor.
    path('peliculas/rating', views.peliculasRating, name='peliculasRating'),
    # Pagina que muestra todas las peliculas ordenadas por el numero de usuarios
    # que las ha marcado como favoritas, de mayor a menor.
    path('peliculas/favoritos', views.peliculasFavorito, name='peliculasFavorito'),
    # Pagina que muestra todos los generos.
    path('generos/', views.generos, name='generos'),
    # Pagina que muestra todas las peliculas de un genero.
    path('generos/<int:genero_id>/', views.genero, name='genero'),
    # Pagina para escribir una review.
    path('review/<int:pelicula_id>/', views.nuevaReview, name='nuevaReview'),
    # Pagina para editar una review.
    path('review/editar/<int:review_id>/', views.editarReview, name='editarReview'),
    # Pagina para borrar una review.
    path('review/borrar/<int:review_id>/', views.borrarReview, name='borrarReview'),
]

clon_imdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('appIMDb.urls')),
]

users/urls.py
""" Define los patrones URL para users. """

from django.urls import path, include

from . import views

app_name = "urls"
urlpatterns = [
    # Incluye las urls de auth default.
    path('', include('django.contrib.auth.urls')),
    # Pagina para crear una cuenta.
    path('registro/', views.registro, name='registro'),
    # Pagina para visualizar las peliculas favoritas.
    path('perfil/favoritas', views.listaFav, name='listaFav'),
    # Pagina para agregar a favoritos.
    path('fav/<int:pelicula_id>/', views.marcarFav, name='marcarFav', ),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from appIMDb.models import Pelicula

def registro(request):
    """Registro para un nuevo usuario."""

    if request.method != 'POST':
        # Muestra el formulario de registro en blanco.
        form = UserCreationForm()
    else:
        # Procesa el formulario llenado.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            nuevoUsuario = form.save()
            # Loggea al usuario y lo redirecciona a la pagina principal
            login(request, nuevoUsuario)
            return redirect('appIMDb:index')

    # Recarga la  pagina y muestra un formulario en blanco, o un formulario
    # que no sea valido.
    context = {'form': form}
    return render(request, 'registration/registro.html', context)

@login_required
def listaFav(request):

    peliculas = Pelicula.objects.filter(favoritos=request.user)

    context = {'peliculas': peliculas}
    return render(request, 'dashboard/favoritos.html', context)

@login_required
def marcarFav(request, pelicula_id):
    """Usuario marca una pelicula como de sus favoritas."""

    pelicula = get_object_or_404(Pelicula, id=pelicula_id)

    if pelicula.favoritos.filter(id=request.user.id).exists():
        # Elimina la pelicula de las favoritas del usuario
        pelicula.favoritos.remove(request.user)
    else:
        pelicula.favoritos.add(request.user)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

users/templates/dashboard/favoritos.html
{% extends 'appIMDb/base.html' %}

{% block page_header %}

<h1 class="display-2">
    <div class="text-center fw-bold">
        Favoritos
    </div>
</h1>

{% endblock page_header %}

{% block content %}
    <div class="favoritos">
        {% for pelicula in peliculas %}
            <div class="card" style="width: 18rem;">
                <a href="{% url 'appIMDb:pelicula' pelicula.id %}">
                    <img src="{{ pelicula.portada }}" alt="Portada"
                        class="card-img-top">
                </a>
                <div class="card-body">
                    <p class="card-text titulo">
                        {{ pelicula.titulo }}
                    </p>
                </div>
            </div>
        {% empty %}
            <a href="{% url 'appIMDb:peliculas' %}"
                class="btn btn-primary btn-lg">
                Agrega peliculas a tus favoritos
            </a>
        {% endfor %}
    </div>

{% endblock content %}